name: Montrek TestSuite Template

on:
  workflow_call:
    inputs:
      montrek_base_version:
        required: true
        type: string
      montrek_project:
        required: true
        type: string
    secrets:
      PAT:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ci_pipe_pssw
          POSTGRES_DB: montrek_ci_pipe_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Clone Montrek Repository
        uses: actions/checkout@master
        with:
          repository: chrishombach/montrek
          token: ${{ secrets.PAT }}
          path: ./montrek
          ref: ${{ inputs.montrek_base_version }}

      - name: Checkout PR code or main
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          path: ./montrek/montrek/${{ inputs.montrek_project }}

      - name: Install Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python Dependencies
        run: ./montrek/bin/sync-local-python-env.sh

      - name: Setup env
        run: |
          ENVPATH="./montrek/.env"
          echo "DB_ENGINE=postgres" >> $ENVPATH
          echo "DB_PORT=5432" >> $ENVPATH
          echo "DB_USER=postgres" >> $ENVPATH
          echo "DB_PASSWORD=ci_pipe_pssw" >> $ENVPATH
          echo "DB_NAME=montrek_ci_pipe_db" >> $ENVPATH
          echo "DB_HOST=0.0.0.0" >> $ENVPATH
          echo "SECRET_KEY=testkey" >> $ENVPATH

      - name: Run Tests and Coverage
        run: |
          cd montrek/montrek
          python manage.py test ${{ inputs.montrek_project }} --exclude-tag=functional --parallel
